defaults:
  - base_pytorch_algo # inherits from configurations/algorithm/base_algo.yaml

arch: resnet18
num_class: 10
in_channels: 3
lr: ${experiment.training.lr}
data_mean: ${dataset.mean} # inherits from 'configurations/dataset/example_cifar10.yaml'
data_std: ${dataset.std} # inherits from 'configurations/dataset/example_cifar10.yaml'
classes: ${dataset.classes} # inherits from 'configurations/dataset/example_cifar10.yaml'
