# configuration parsing starts here
defaults:
  - experiment: example_classification # experiment yaml file name in configurations/experiments folder [fixme]
  - dataset: example_cifar10 # dataset yaml file name in configurations/dataset folder [fixme]
  - algorithm: example_classifier # algorithm yaml file name in configurations/algorithm folder [fixme]

debug: false

wandb:
  entity: scene-representation-group # wandb account name / organization name
  project: example # wandb project name to log to [fixme]
  mode: dryrun # set wandb logging to online, offline or dryrun
  resume: null # wandb run id if resume training from logged checkpoints [fixme]

